# A file to clear project files for fresh test

import os

os.remove('Jan_Log.txt')
print('.')
os.remove('Feb_Log.txt')
print('.')
os.remove('Mar_Log.txt')
print('.')
os.remove('Apr_Log.txt')
print('.')
os.remove('May_Log.txt')
print('.')
os.remove('Jun_Log.txt')
print('.')
os.remove('Jul_Log.txt')
print('.')
os.remove('Aug_Log.txt')
print('.')
os.remove('Sep_Log.txt')
print('.')
os.remove('Oct_Log.txt')
print('.')
os.remove('Nov_Log.txt')
print('.')
os.remove('Dec_Log.txt')
print('.')
os.remove('AWS_Log.txt')
print('.')

print('Files Removed.')
